### ISSUE TITLE
Panic with too many voronoi iterations

### ISSUE THREAD

**Issue by jneem** [matze/inkdrop#3]
With the attached image, I'm getting (random but pretty consistent) panics happening with 4 or more voronoi iterations:

```console
cargo run --release --bin inkdrop -- --input head.png --svg head.svg --voronoi-iterations=4 --draw-points
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/inkdrop --input bong-head.png --svg bong-head.svg --voronoi-iterations=4 --draw-points`
[2024-02-18T22:34:40Z INFO  inkdrop] Sample points
[2024-02-18T22:34:40Z INFO  inkdrop] Move points
thread 'main' panicked at /home/jneeman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voronator-0.2.0/src/delaunator.rs:846:63:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The unwrap is coming from a `partial_cmp(<float>, <float>).unwrap()` inside delaunator, so I guess there is a NaN appearing somewhere...

![head](https://github.com/matze/inkdrop/assets/1448113/65ae93c7-6aa6-486f-91d8-42b76c859db9)

**Comment by matze** [comment]
Thanks for the repro, indeed the issue were NaNs that are filtered out now. Not perfect because it does not tackle the root cause but in most cases there is no noticeable difference. In you head example, there were four broken points.
